name: codecov
on: 
  pull_request:

jobs:
  run-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit
          fail_ci_if_error: ${{ github.repository == 'e-mission/e-mission-phone' }}
          
      
